corridaCompartilhada/core/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index$', views.index, name='index'),
    
]

corridaCompartilhada/corrida/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # url(r'^cadastro/$', views.index, name='index'),
    url(r'^listagem/motoristas$', views.listagemMotoristas, name='listagemMotoristas'),
    url(r'^listagem/passageiros$', views.listagemPassageiros, name='listagemPassageiros'),
    url(r'^listagem/corridas$', views.listagemCorridas, name='listagemCorridas'),

    url(r'^cadastro/motoristas$', views.cadastroMotoristas, name='cadastroMotoristas'),
    url(r'^cadastro/passageiros$', views.cadastroPassageiros, name='cadastroPassageiros'),
    url(r'^cadastro/corridas$', views.cadastroCorridas, name='cadastroCorridas'),
]

corridaCompartilhada/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from .core import views as coreViews

urlpatterns = [
                  url(r'^', include('corridaCompartilhada.core.urls', namespace='core')),
                  url(r'^corridas', include('corridaCompartilhada.corrida.urls', namespace='corridas')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^', coreViews.not_found, name='not_found'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

corridaCompartilhada/core/models.py
from django.db import models

# Create your models here.

corridaCompartilhada/corrida/models.py
from django.db import models


class Passageiro(models.Model):
    nome = models.CharField('Nome', max_length=40, null=False)
    data_nascimento = models.DateField('DataNascimento', null=False)
    cpf = models.CharField('CPF', max_length=11, null=False)
    sexo = models.CharField('Sexo', max_length=1, null=False)

    def __str__(self):
        return "{} - {}".format(self.nome, self.cpf)

    @models.permalink
    def cadastroUsuario(self):
        return ('corridas:cadastroPassageiros', (), {})


class Motorista(models.Model):
    nome = models.CharField('Nome', max_length=40, null=False)
    data_nascimento = models.DateField('DataNascimento', null=False)
    cpf = models.CharField('CPF', max_length=11, null=False)
    sexo = models.CharField('Sexo', max_length=1, null=False)
    ativo = models.BooleanField('Ativo', default=True)
    modelo_carro = models.CharField('ModeloCarro', max_length=40)

    def __str__(self):
        return "{} - {} - {}".format(self.nome, self.cpf, self.modelo_carro)

    @models.permalink
    def cadastroUsuario(self):
        return ('corridas:cadastroMotoristas', (), {})


class Corrida(models.Model):
    motorista = models.ForeignKey(Motorista)
    passageiro = models.ForeignKey(Passageiro)
    valor = models.DecimalField('Valor', decimal_places=2, max_digits=10)

    def __str__(self):
        return "Motorista: {} Passageiro: {} Preço: {}".format(self.motorista.nome, self.passageiro.nome, self.valor)

    @models.permalink
    def cadastro(self):
        return ('corridas:cadastroCorridas', (), {})

corridaCompartilhada/core/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    template = 'index.html'
    context = {}
    return render(request, template, context)


def not_found(request):
    template = '404.html'
    context = {}
    return render(request, template, context)

corridaCompartilhada/corrida/views.py
from django.shortcuts import render, redirect

from .models import Motorista, Passageiro, Corrida
from ..core import views

# Create your views here.

def listagemMotoristas(request):
    template = 'lista.html'
    usuarios = Motorista.objects.all()
    context = {
        'nomeUsuario': 'Motoristas',
        'usuarios': usuarios,
        'genero': 'o',
    }
    return render(request, template, context)


def listagemPassageiros(request):
    template = 'lista.html'
    usuarios = Passageiro.objects.all()
    context = {
        'nomeUsuario': 'Passageiros',
        'usuarios': usuarios,
        'genero': 'o',
    }
    return render(request, template, context)


def listagemCorridas(request):
    template = 'listaCorridas.html'
    usuarios = Corrida.objects.all()
    context = {
        'nomeUsuario': 'Corridas',
        'usuarios': usuarios,
        'genero': 'a',
    }
    return render(request, template, context)


def cadastroMotoristas(request):
    if request.method == 'GET':
        return formCadastro(request)

    elif request.method == 'POST':
        motorista = Motorista.objects.create(
            nome=request.POST.get('nome'),
            data_nascimento=request.POST.get('dataNascimento'),
            cpf=request.POST.get('cpf'),
            sexo=request.POST.get('sexo'),
            modelo_carro=request.POST.get('modeloCarro'),
            ativo=(request.POST.get('modeloCarro') == 'Ativo')
        )

        motorista.save()

        return redirect('corridas:listagemMotoristas')

    return views.not_found(request)


def cadastroPassageiros(request):
    if request.method == 'GET':
        return formCadastro(request, Passageiro(), "Passageiros")

    elif request.method == 'POST':
        passageiro = Passageiro.objects.create(
            nome=request.POST.get('nome'),
            data_nascimento=request.POST.get('dataNascimento'),
            cpf=request.POST.get('cpf'),
            sexo=request.POST.get('sexo')
        )

        passageiro.save()

        return redirect('corridas:listagemPassageiros')

    return views.not_found(request)


def formCadastro(request, user=Motorista(), descricao='Motoristas'):
    template = 'cadastroUsuarios.html'
    context = {
        'nomeUsuario': descricao,
        'user': user,
    }
    return render(request, template, context)


def formCorrida(request):
    template = 'cadastroCorrida.html'

    motoristas = Motorista.objects.all()
    passageiros = Passageiro.objects.all()

    context = {
        'nomeUsuario': 'Corridas',
        'motoristas': motoristas,
        'passageiros': passageiros
    }
    return render(request, template, context)


def cadastroCorridas(request):
    if request.method == 'GET':
        return formCorrida(request)

    elif request.method == 'POST':
        motoristaCPF = str(request.POST.get('motorista')).split(' - ')[1]
        passageiroCPF = str(request.POST.get('passageiro')).split(' - ')[1]
        valor = request.POST.get('preco')

        motorista = Motorista.objects.filter(cpf=motoristaCPF).first()
        passageiro = Passageiro.objects.filter(cpf=passageiroCPF).first()

        corrida = Corrida.objects.create(
            passageiro=passageiro,
            motorista=motorista,
            valor=valor
        )

        corrida.save()

        return redirect('corridas:listagemCorridas')

    return views.not_found(request)

corridaCompartilhada/core/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="pt-br">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Corrida Compartilhada</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/shop-item.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:index'%}">Corrida Compartilhada</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLista" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Lista
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'corridas:listagemMotoristas' %}">Motoristas</a>
                        <a class="dropdown-item" href="{% url 'corridas:listagemPassageiros' %}">Passageiros</a>
                        <a class="dropdown-item" href="{% url 'corridas:listagemCorridas' %}">Corridas</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuCadastro" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Cadastro
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'corridas:cadastroMotoristas' %}">Motoristas</a>
                        <a class="dropdown-item" href="{% url 'corridas:cadastroPassageiros' %}">Passageiros</a>
                        <a class="dropdown-item" href="{% url 'corridas:cadastroCorridas' %}">Corridas</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{%block container%}{%endblock container%}
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Miguel 2018</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

corridaCompartilhada/core/templates/index.html
{% extends "base.html" %}
{%load static%}

{% block container%}

<div class="jumbotron">
    <h1>Corridas Compartilhadas</h1>
    <div><h3>Descrição</h3>
        <div class="container">
            <p class="lead">
                Neste sistema será possível cadastrar motoristas com Nome, Data de Nascimento, CPF,
                Modelo do carro, Status e Sexo, todos os campos são obrigatórios.
                Quando um motorista entrar em período de férias será possível alterar seu status de Ativo, para Inativo
                e o sistema deve conter uma consulta aos motoristas já cadastrados.
            <p class="collapse lead" id="descricao">
                Para o cadastro de passageiros o sistema precisa de Nome do Passageiro, Data de
                Nascimento, CPF e Sexo, todos os campos são obrigatórios. Nosso cliente também precisará
                consultar os passageiros já cadastrados no sistema.
                Por fim será possível registrar e consultar uma lista de corridas.
                Para registrar uma corrida será necessário informar qual o motorista, qual o passageiro e o valor da
                corrida.
            </p>
            <br/>
            <a class="btn btn-outline-secondary" data-toggle="collapse" href="#descricao" role="button"
               aria-expanded="false" aria-controls="collapseExample">
                Ler Mais...
            </a>
            </p>
        </div>
    </div>
</div>
{% endblock container %}

corridaCompartilhada/corrida/templates/cadastroCorrida.html
{%extends "base.html"%}
{%load static%}
{%block container%}
<div class="jumbotron">
    <h3>Cadastro de Corridas:</h3>
    <div class="container">
        <form name="form-cadastro" action="" id="form-cadastro" role="form" method="POST">{% csrf_token %}
            <div class="form-row">
                <div class="mb-4">
                    <label for="motorista">Motorista</label>
                    <select class="form-control" id="motorista" name="motorista" required>

                        {%for motorista in motoristas%}
                        <option>{{motorista}}</option>
                        {%endfor%}

                    </select>
                </div>
                <div class="col-lf-4 mb-3">
                    <label for="passageiro">Passageiro</label>
                    <select class="form-control" id="passageiro" name="passageiro" required>
                        {%for passageiro in passageiros%}
                        <option>{{passageiro}}</option>

                        {%endfor%}
                    </select>

                </div>

                <div class="col-md-3 mb-3">
                    <label for="preco">Preço</label>
                    <div class="input-group">
                        <input type="number" min="0" step="0.01" data-number-to-fixed="2"
                               data-number-stepfactor="100" class="form-control currency" name="preco" id="preco" required/>
                    </div>

                </div>
            </div>
            <button class="btn btn-secundary" type="submit">Cadastrar</button>
        </form>
    </div>
</div>
{%endblock%}
<!--Js para validação de formularios-->
<script src="{% static 'js/validateCadastro.js' %}"></script>

corridaCompartilhada/corrida/templates/cadastroUsuarios.html
{%extends "base.html"%}
{%load static%}
{%block container%}
<div class="jumbotron">
    <h3>Cadastro de {{nomeUsuario}}:</h3>
    <div class="container">
        <form role="form" action="{{user.cadastroUsuario}}" method="POST">{% csrf_token %}
            <div class="form-row">
                <div class="col-md-4 mb-3">
                    <label>Nome</label>
                    <input type="text" class="form-control" id="nome" name="nome" required>
                    <!--<div class="valid-feedback">-->
                    <!--Looks good!-->
                    <!--</div>-->
                </div>
                <div class="col-md-4 mb-3">
                    <label for="sexo">Sexo</label>
                    <select class="form-control" id="sexo" name="sexo">
                        <option>Feminino</option>
                        <option>Masculino</option>
                        <option>Outro</option>
                    </select>
                </div>
                {%if nomeUsuario == 'Motoristas'%}
                <div class="col-md-4 mb-3">
                    <label for="modeloCarro">Modelo do Carro</label>
                    <input type="text" class="form-control" id="modeloCarro" name="modeloCarro" required>
                </div>
                {%endif%}
                <div class="col-md-4 mb-5">
                    <label for="cpf">CPF</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="cpf" name="cpf"
                               aria-describedby="inputGroupPrepend3" placeholder="000.000.000-00" maxlength="11"
                               onblur="validaCPF(this.value)" required>
                    </div>
                </div>


                <div class="col-md-3 mb-3">
                    <label for="dataNascimento">Data de Nascimento</label>
                    <div class='input-group date'>
                        <input type='date' class="form-control" id='dataNascimento' name="dataNascimento"
                               onblur="maiorDeIdade(this.value)"
                               required/>
                    </div>
                </div>
                {%if nomeUsuario == 'Motoristas'%}
                <div class="col-md-4 mb-3">
                    <label for="sexo">Status</label>
                    <select class="form-control" id="status" name="status">
                        <option>Ativo</option>
                        <option>Inativo</option>
                    </select>
                </div>
                {%endif%}
            </div>
            <button class="btn btn-secundary" type="submit" id="btn-cadastrar">Cadastrar</button>
        </form>
    </div>
</div>
<script src="{% static 'js/validateCadastro.js' %}"></script>
{%endblock%}

corridaCompartilhada/corrida/templates/lista.html
{%extends "base.html"%}
{%block container%}
<div class="jumbotron">
    <h3>Consulta de {{nomeUsuario}}:</h3>
    {%if usuarios%}
    <table class="table table-striped table-dark">

        <thead>
        <tr>
            <th>Nome</th>
            <th>Data nascimento</th>
            <th>CPF</th>
            <th>Sexo</th>
            {%if nomeUsuario == 'Motoristas'%}
            <th>Ativo</th>
            {%endif%}
        </tr>
        </thead>
        <tbody>
        {%for user in usuarios%}
        <tr>
            <th>{{user.nome}}</th>
            <th>{{user.data_nascimento}}</th>
            <th>{{user.cpf}}</th>
            <th>{{user.sexo}}</th>
            {%if nomeUsuario == 'Motoristas'%}

            <th>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="customCheck1"
                           {%if user.ativo %} checked
                           {%endif%} disabled>
                    <label class="custom-control-label" for="customCheck1"></label>
                </div>
            </th>

            {%endif%}
        </tr>
        {%endfor%}
        </tbody>
    </table>
    {%else%}
    <h2>Não há {{nomeUsuario}} cadastrad{{genero}}s</h2>
    {%endif%}
</div>
{%endblock container%}

corridaCompartilhada/corrida/templates/listaCorridas.html
{%extends "base.html"%}
{%block container%}
<div class="jumbotron">
    <h3>Consulta de {{nomeUsuario}}:</h3>
    {%if usuarios%}
    <table class="table table-striped table-dark">

        <thead>
        <tr>
            <th>Motorista</th>
            <th>Passsageiro</th>
            <th>Valor</th>
        </tr>
        </thead>
        <tbody>
        {%for user in usuarios%}
        <tr>
            <th>{{user.motorista}}</th>
            <th>{{user.passageiro}}</th>
            <th>{{user.valor}}</th>
        </tr>
        {%endfor%}
        </tbody>
    </table>
    {%else%}
    <h2>Não há {{nomeUsuario}} cadastrad{{genero}}s</h2>
    {%endif%}
</div>
{%endblock container%}